---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# python-project-tag-push-verify-action
name: '🐍 Check Pushed Tag Matches Project Version'
description: 'Checks a pushed tag matches the declared Python project version'

inputs:
  exit_on_fail:
    description: 'When set true will exit with error on version mismatch'
    required: false
    default: 'true'
  path_prefix:
    description: 'Directory location containing project code'
    required: false
  # For testing purposes ONLY, do not use
  test_tag:
    description: 'Undocumented test input/value'
    required: false

outputs:
  match:
    description: 'Set true when pushed tags match Python project metadata'
    value: "${{ steps.verify.outputs.match }}"
  matched_tag:
    description: 'Matched tag/version value'
    value: "${{ steps.verify.outputs.matched_tag }}"

runs:
  using: 'composite'
  steps:
    - name: 'Retrieve Python project version'
      id: fetch
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/python-project-version-action@cd2312738a1ed0e6732315037dc32a76adaf1ed5 # v0.2.1
      with:
        path_prefix: "${{ inputs.path_prefix }}"

    - name: 'Check tag/version for match'
      id: verify
      shell: bash
      env:
        EXIT_ON_FAIL: "${{ inputs.exit_on_fail }}"
        REF_TYPE: "${{ github.ref_type }}"
        REF_NAME: "${{ github.ref_name }}"
        TEST_TAG: "${{ inputs.test_tag }}"
        PROJECT_VERSION: "${{ steps.fetch.outputs.python_project_version }}"
      run: |
        # Check tag/versions for consistency
        exit_on_fail="$EXIT_ON_FAIL"
        # This code path is only conditionally triggered for testing purposes
        if [ "$REF_TYPE" = 'tag' ]; then
          pushed_tag="$REF_NAME"
        else
          pushed_tag="$TEST_TAG"
        fi

        # Validate outputs from previous action
        project_version="$PROJECT_VERSION"
        if [ -z "$project_version" ]; then
          echo "The python project version string was empty ❌"
          echo "Check action/workflow inputs/output/variables"
          exit 1
        fi

        compareTag() {
          if [ "$1" = "$2" ]; then
            echo "true"
          else
            echo "false"
          fi
        }

        # Display the compared versions
        echo "Project version: $project_version"
        echo "Pushed tag:      $pushed_tag"

        # Perform comparison check
        result=$(compareTag "$pushed_tag" "$project_version")
        if [ "$result" != "true" ]; then
          # If present, strip the leading "v" character and retry
          if [[ "$pushed_tag" == v* ]]; then
            pushed_tag="${pushed_tag:1}"
          fi
          result=$(compareTag "$pushed_tag" "$project_version")
        fi

        # Set output values
        echo "match=$result" >> "$GITHUB_OUTPUT"
        echo "matched_tag=$pushed_tag" >> "$GITHUB_OUTPUT"

        if [ "$result" = "true" ]; then
          echo 'Pushed tag matches version in Python project ✅'
        else
          echo 'Error: pushed tag does NOT match Python project version ❌'
          echo 'Error: pushed tag does NOT match Python project version ❌' \
            >> "$GITHUB_STEP_SUMMARY"
          if [ "f$exit_on_fail" = "ftrue" ]; then
            exit 1
          fi
        fi
