---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Perform setup prior to running test(s)
      - name: "Checkout sample project repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: "lfreleng-actions/test-python-project"
          path: "test-python-project"

      # Test valid tag comparison
      - name: "Run Action: ${{ github.repository }}"
        uses: ./
        with:
          path_prefix: "test-python-project/"
          exit_on_fail: "false"
          test_tag: "0.0.1"

      # Test valid tag comparison (variation)
      - name: "Run Action: ${{ github.repository }}"
        uses: ./
        with:
          path_prefix: "test-python-project/"
          exit_on_fail: "false"
          test_tag: "v0.0.1"

      # Test invalid tag comparison
      - name: "Run Action: ${{ github.repository }}"
        uses: ./
        continue-on-error: true
        with:
          path_prefix: "test-python-project/"
          exit_on_fail: "false"
          test_tag: "0.1.0"

      - name: "Validating local action: ${{ github.repository }}"
        shell: bash
        run: |
          # Local action validation
          echo "Validating local action: ${{ github.repository }}"
          echo "Validation step summary output" >> "$GITHUB_STEP_SUMMARY"
